Repository tkestack/tke, pull requests merged in 2019-11, with the labels that each got.

#12 ci: test pr
  README.md
  pkg/platform/provider/baremetal/machine/create.go
Labels: size/XS

#13 feat: add redis cache to registry
  pkg/registry/apis/config/helpers_test.go
  pkg/registry/apis/config/types.go
  pkg/registry/apis/config/v1/types.go
  pkg/registry/apis/config/v1/zz_generated.conversion.go
  pkg/registry/apis/config/v1/zz_generated.deepcopy.go
  pkg/registry/apis/config/validation/validation.go
  pkg/registry/apis/config/validation/validation_test.go
  pkg/registry/apis/config/zz_generated.deepcopy.go
  pkg/registry/distribution/distribution.go
Labels: lgtm, size/L

#14 refactor(tke-platform-api tke-platform-controller tke-installer): cha…
  build/docker/baremetal-cluster-provider/Dockerfile
  build/docker/baremetal-machine-provider/Dockerfile
  build/docker/tools/tke-installer/build.sh
  cmd/baremetal-cluster-provider/app/app.go
  cmd/baremetal-cluster-provider/plugin.go
  cmd/baremetal-machine-provider/app/app.go
  cmd/baremetal-machine-provider/plugin.go
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
  cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
  cmd/tke-installer/app/options/options.go
  cmd/tke-platform-api/app/config/config.go
  cmd/tke-platform-api/app/options/options.go
  cmd/tke-platform-controller/app/config/config.go
  cmd/tke-platform-controller/app/options/options.go
  cmd/tke-platform-controller/app/run.go
  pkg/app/app.go
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/config/config.go
  pkg/platform/provider/baremetal/constants/constants.go
  pkg/platform/provider/baremetal/machine/create.go
  pkg/platform/provider/baremetal/machine/provider.go
  pkg/platform/provider/baremetal/phases/gpu/gpu.go
  pkg/platform/provider/cluster/client.go
  pkg/platform/provider/cluster/interface.go
  pkg/platform/provider/cluster/rpc.go
  pkg/platform/provider/cluster/server.go
  pkg/platform/provider/cluster/types.go
  pkg/platform/provider/config/config.go
  pkg/platform/provider/machine/client.go
  pkg/platform/provider/machine/interface.go
  pkg/platform/provider/machine/rpc.go
  pkg/platform/provider/machine/server.go
  pkg/platform/provider/machine/types.go
  pkg/platform/provider/options/options.go
Labels: size/XXL

#15 feat: remove tea-cli config
  web/console/.eslintignore
  web/console/package.json
  web/console/tsconfig.json
  web/installer/tsconfig.json
Labels: size/XS

#22 fix: can't add node
  cmd/tke-platform-api/app/config/config.go
  cmd/tke-platform-controller/app/config/config.go
Labels: size/XS

#24 fix: add missing baremetal provider manifests for release
  build/docker/tools/tke-installer/build.sh
Labels: size/XS
