Repository tkestack/tke, pull requests merged in 2019-12, with the labels that each got.

#27 fix: unable to delete business namespaces
  pkg/business/registry/namespace/storage/storage.go
  pkg/business/registry/namespace/strategy.go
  pkg/business/registry/rest/rest.go
Labels: lgtm, size/M

#30 feat: Support providers option to tke-platform-{api,controller}
  cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
  cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
  cmd/tke-platform-api/app/config/config.go
  cmd/tke-platform-api/app/options/options.go
  cmd/tke-platform-controller/app/config/config.go
  cmd/tke-platform-controller/app/options/options.go
  pkg/platform/provider/options/options.go
Labels: size/L

#40 Add Prometheus doc
  hack/addon/readme/Prometheus.md
Labels: size/M

#21 update storage group name
  pkg/platform/registry/cluster/storage/csioperator.go
  pkg/platform/registry/cluster/storage/pvcr.go
Labels: lgtm, size/XS

#17 api group of lbcf modified to lbcf.tkestack.io
  pkg/platform/controller/addon/lbcf/controller.go
  pkg/platform/controller/addon/lbcf/images/images.go
  pkg/platform/registry/cluster/storage/lbcf_backendgroup.go
  pkg/platform/registry/cluster/storage/lbcf_backendrecord.go
  pkg/platform/registry/cluster/storage/lbcf_driver.go
  pkg/platform/registry/cluster/storage/lbcf_loadbalancer.go
Labels: lgtm, size/M

#47 Update tapp group name
  pkg/platform/registry/cluster/storage/tappcontroller.go
Labels: size/XS

#48 Update cronhpa group name
  pkg/platform/registry/cluster/storage/cronhpa.go
Labels: size/XS

#49 fix:notify template list filtered by TenantID always get empty result
  pkg/notify/registry/template/storage/storage.go
  pkg/notify/registry/template/strategy.go
Labels: lgtm, size/M

#54 Fix: misleading variable names in template storage
  pkg/notify/registry/template/storage/storage.go
Labels: lgtm, size/S

#60 Fix/fix resource version
  web/console/config/resource/common/apiVersion.ts
  web/console/src/modules/cluster/actions/resourceActions.ts
  web/console/src/modules/cluster/components/resource/resourceEdition/EditLbcfBackGroupPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditLbcfPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx
  web/console/src/modules/common/components/index.ts
Labels: size/S

#62 Add installation guides
  README.md
  docs/devel/install.md
  docs/images/TKEStackHighLevelArchitecture@2x.png
  docs/images/install/Picture10.png
  docs/images/install/Picture2.png
  docs/images/install/Picture3.png
  docs/images/install/Picture4.png
  docs/images/install/Picture5.png
  docs/images/install/Picture6.png
  docs/images/install/Picture7.png
  docs/images/install/Picture8.png
  docs/images/install/Picture9.png
Labels: size/M

#68 fix: etcd use headless service, instead of using cluster IP with LB
  cmd/tke-installer/app/installer/manifests/etcd/etcd.yaml
Labels: size/XS

#69 docs: add installer
  README.md
  docs/user/tke-installer/README.md
  docs/user/tke-installer/images/step-1.png
  docs/user/tke-installer/images/step-2.png
  docs/user/tke-installer/images/step-3.png
  docs/user/tke-installer/images/step-4.png
  docs/user/tke-installer/images/step-5.png
  docs/user/tke-installer/images/step-6.png
  docs/user/tke-installer/images/step-7.png
  docs/user/tke-installer/images/step-8.png
  docs/user/tke-installer/images/step-9.png
  docs/user/tke-installer/installer-config.md
  docs/user/tke-installer/installing-offline.md
  docs/user/tke-installer/introduction.md
  docs/user/tke-installer/normal-installation.md
Labels: size/L

#75 feat: business supports chart group
  api/business/register.go
  api/business/types.go
  api/business/v1/defaults.go
  api/business/v1/generated.pb.go
  api/business/v1/generated.proto
  api/business/v1/register.go
  api/business/v1/types.go
  api/business/v1/types_swagger_doc_generated.go
  api/business/v1/zz_generated.conversion.go
  api/business/v1/zz_generated.deepcopy.go
  api/business/v1/zz_generated.defaults.go
  api/business/zz_generated.deepcopy.go
  api/client/clientset/internalversion/typed/business/internalversion/business_client.go
  api/client/clientset/internalversion/typed/business/internalversion/chartgroup.go
  api/client/clientset/internalversion/typed/business/internalversion/fake/fake_business_client.go
  api/client/clientset/internalversion/typed/business/internalversion/fake/fake_chartgroup.go
  api/client/clientset/internalversion/typed/business/internalversion/generated_expansion.go
  api/client/clientset/versioned/typed/business/v1/business_client.go
  api/client/clientset/versioned/typed/business/v1/chartgroup.go
  api/client/clientset/versioned/typed/business/v1/fake/fake_business_client.go
  api/client/clientset/versioned/typed/business/v1/fake/fake_chartgroup.go
  api/client/clientset/versioned/typed/business/v1/generated_expansion.go
  api/client/informers/externalversions/business/v1/chartgroup.go
  api/client/informers/externalversions/business/v1/interface.go
  api/client/informers/externalversions/generic.go
  api/client/informers/internalversion/business/internalversion/chartgroup.go
  api/client/informers/internalversion/business/internalversion/interface.go
  api/client/informers/internalversion/generic.go
  api/client/listers/business/internalversion/chartgroup.go
  api/client/listers/business/internalversion/expansion_generated.go
  api/client/listers/business/v1/chartgroup.go
  api/client/listers/business/v1/expansion_generated.go
  api/openapi/zz_generated.openapi.go
  cmd/tke-business-controller/app/business.go
  cmd/tke-business-controller/app/controller.go
  go.mod
  go.sum
  pkg/business/controller/chartgroup/chartgroup_cache.go
  pkg/business/controller/chartgroup/chartgroup_controller.go
  pkg/business/controller/chartgroup/chartgroup_health.go
  pkg/business/controller/chartgroup/deletion/chartgroup_resources_deleter.go
  pkg/business/registry/chartgroup/storage/storage.go
  pkg/business/registry/chartgroup/strategy.go
  pkg/business/registry/chartgroup/validation.go
  pkg/business/registry/rest/rest.go
  pkg/business/util/filter.go
Labels: lgtm, size/XXL

#64 fix: can NOT cascadingly delete projects and namespaces
  pkg/business/controller/project/deletion/projected_resources_deleter.go
  pkg/business/registry/imagenamespace/storage/storage.go
  pkg/business/registry/namespace/storage/storage.go
  pkg/business/registry/project/storage/storage.go
  pkg/business/registry/project/strategy.go
Labels: lgtm, size/L

#80 feat: add job/cronjob resource for apiclient
  pkg/util/apiclient/idempotency.go
  pkg/util/apiclient/install.go
Labels: size/M

#84 fix: check gateway config if not nil
  cmd/tke-installer/app/installer/installer.go
Labels: lgtm, size/XS

#83 fix: not delete imageNamespaces and chartGroups when deleting projects
  go.mod
  go.sum
  pkg/business/controller/project/deletion/projected_resources_deleter.go
Labels: needs-ok-to-test, size/L

#86 fix: issus #77 #76 #71
  web/console/Wrapper.tsx
  web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
  web/console/src/modules/cluster/components/clusterManage/SelectICComputerPanel.tsx
Labels: needs-ok-to-test, size/S

#93 feat: Support self-defined notify webhook
  api/openapi/zz_generated.openapi.go
  api/platform/types.go
  api/platform/v1/generated.pb.go
  api/platform/v1/generated.proto
  api/platform/v1/types.go
  api/platform/v1/types_swagger_doc_generated.go
  api/platform/v1/zz_generated.conversion.go
  pkg/platform/controller/addon/prometheus/controller.go
Labels: lgtm, needs-ok-to-test, size/S

#88 docs: update running locally guide
  build/lib/golang.mk
  cmd/README.md
  docs/devel/running-locally.md
Labels: lgtm, needs-ok-to-test, size/XXL

#97 fix: remove unused error handling
  cmd/tke-notify-controller/app/run.go
  cmd/tke-platform-controller/app/run.go
Labels: lgtm, size/XS

#99 fix: Update tke-notify-controller running locally guide
  docs/devel/running-locally.md
Labels: lgtm, needs-ok-to-test, size/M

#98 fix: typo in prometheus controller
  pkg/platform/controller/addon/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: lgtm, needs-ok-to-test, size/XS

#104 fix: authz handler type error
  build/lib/deploy.mk
  pkg/auth/authorization/util/helpers.go
  pkg/auth/authorization/util/validation.go
  pkg/auth/handler/authn/handler.go
  pkg/auth/handler/authz/handler.go
Labels: lgtm, size/M

#105 fix: auth processUpdate when phase is not terminating
  pkg/auth/controller/group/group_controller.go
  pkg/auth/controller/localidentity/localidentity_controller.go
  pkg/auth/controller/policy/policy_controller.go
  pkg/auth/controller/role/role_controller.go
Labels: size/M
