Repository tkestack/tke, pull requests merged in 2020-01, with the labels that each got.

#107 Fix convert tke resource with multi namespace or cluster
  pkg/auth/filter/filter.go
  pkg/auth/filter/filter_test.go
Labels: size/M

#110 Integrate rook in global cluster
  cmd/tke-installer/app/installer/hooks/post-rook-install
  cmd/tke-installer/app/installer/images/images.go
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/influxdb/influxdb.yaml
  cmd/tke-installer/app/installer/manifests/rook/common.yaml
  cmd/tke-installer/app/installer/manifests/rook/operator.yaml
  cmd/tke-installer/app/installer/manifests/rook/storageclass.yaml
Labels: size/XXL

#111 Disable fs and flex in rook operator
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/rook/operator.yaml
Labels: size/S

#112 Fix: add applicationFullAccess default policy
  hack/auth/category.json
  hack/auth/policy.json
Labels: size/XXL

#118 Fix k8s rest authz and ensure new idp in memory idp map
  cmd/tke-auth-api/app/config/config.go
  cmd/tke-auth-api/app/server.go
  pkg/auth/apiserver/apiserver.go
  pkg/auth/authentication/oidc/identityprovider/ldap/ldap.go
  pkg/auth/authentication/oidc/identityprovider/local/hook_local.go
  pkg/auth/authentication/oidc/identityprovider/local/local.go
  pkg/auth/controller/group/group_controller.go
  pkg/auth/filter/filter.go
  pkg/auth/filter/filter_test.go
  pkg/auth/handler/authz/handler.go
  pkg/auth/registry/group/storage/storage.go
  pkg/auth/registry/identityprovider/storage/storage.go
  pkg/auth/registry/rest/rest.go
Labels: size/L
