Repository tkestack/tke, pull requests merged in 2020-05, with the labels that each got.

#368 fix(log-agent): make logagent running when NumberAvailable is more th…
  pkg/logagent/controller/logagent/logagent_controller.go
Labels: approved, lgtm

#370 feat(notify): add AlarmPolicyType and ReceiverChannelName to notify m…
  api/notify/types.go
  api/notify/v1/conversion.go
  api/notify/v1/generated.pb.go
  api/notify/v1/generated.proto
  api/notify/v1/types.go
  api/notify/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  pkg/notify/controller/messagerequest/controller.go
  pkg/notify/registry/message/strategy.go
Labels: approved, lgtm, size/L

#371 fix(cluster): delete Imported cluster hang in Terminating
  pkg/platform/controller/cluster/cluster_controller.go
Labels: approved, lgtm, size/S

#384 fix: cluster gpu type validation
  api/platform/validation/cluster.go
Labels: size/XS

#377 fix(galaxy-ipam): fix galaxy-ipam service
  pkg/platform/controller/addon/ipam/ipam_controller.go
Labels: size/XS

#387 fix(cluster): scale sub-resources of workload cannot be updated using…
  pkg/platform/proxy/apps/deployment/storage/storage.go
  pkg/platform/proxy/apps/replicaset/storage/storage.go
  pkg/platform/proxy/apps/statefulset/storage/storage.go
  pkg/platform/proxy/core/replicationcontroller/storage/storage.go
Labels: approved, size/L

#385 fix: cluster gpu type validation
  api/platform/validation/cluster.go
Labels: lgtm, size/XS

#373 fix: business portal missed lister interfaces
  pkg/business/registry/portal/storage/storage.go
Labels: size/XS

#389 docs: update QRcode && Installation requirement && FAQ
  docs/guide/zh-CN/FAQ/events.md
  docs/guide/zh-CN/installation/installation-requirement.md
  docs/images/wechat.jpeg
Labels: approved, do-not-merge/contains-merge-commits, size/XS

#395 fix(cluster): addon RESTs overwrite apiserver path when sending request
  pkg/platform/registry/cluster/storage/cronhpa.go
  pkg/platform/registry/cluster/storage/csioperator.go
  pkg/platform/registry/cluster/storage/helm.go
  pkg/platform/registry/cluster/storage/lbcf_backendgroup.go
  pkg/platform/registry/cluster/storage/lbcf_backendrecord.go
  pkg/platform/registry/cluster/storage/lbcf_driver.go
  pkg/platform/registry/cluster/storage/lbcf_loadbalancer.go
  pkg/platform/registry/cluster/storage/logcollector.go
  pkg/platform/registry/cluster/storage/pvcr.go
  pkg/platform/registry/cluster/storage/tappcontroller.go
Labels: size/M

#392 fix: bump galaxy/ipam version to fix host port issue
  pkg/platform/controller/addon/ipam/images/images.go
  pkg/platform/provider/baremetal/phases/galaxy/images/images.go
Labels: size/XS

#391 fix(log-agent): filedownload should be longrunning in log-agent-api a…
  cmd/tke-gateway/app/config/config.go
  cmd/tke-logagent-api/app/config/config.go
Labels: size/XS

#396 fix(cluster): url path in requests sent by addon RESTs should be cut
  pkg/platform/util/location.go
Labels: size/S

#400 build: remove useless target
  build/lib/asset.mk
Labels: approved, lgtm, size/XS

#403 fix(gateway): web route
  pkg/gateway/assets/assets.go
Labels: approved, lgtm, size/XS

#405 feat: support recovering from failed namespaces
  pkg/business/controller/namespace/namespace_controller.go
Labels: approved, lgtm, size/M

#406 fix(cluster): audit file path
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/kubeadm.go
  pkg/platform/provider/baremetal/constants/constants.go
  pkg/platform/provider/baremetal/phases/addons/cniplugins/cniplugins.go
Labels: approved, lgtm, size/M

#411 docs: update
  docs/guide/zh-CN/README.md
  docs/guide/zh-CN/installation/installation-requirement.md
  docs/guide/zh-CN/products/controlpannel.md
  docs/guide/zh-CN/products/platform/cluster.md
  docs/images/basicinformation.png
  docs/images/nodecaozuo.png
  docs/images/nodes.png
  docs/images/nodespod.png
  docs/images/wechat.jpeg
Labels: approved, lgtm, size/L

#412 fix(installer): redirect useless error message during installation, close #407
  build/docker/tools/tke-installer/install.sh
Labels: approved, lgtm, size/XS

#413 feat(notify): add clusterID to notify message
  api/notify/types.go
  api/notify/v1/conversion.go
  api/notify/v1/generated.pb.go
  api/notify/v1/generated.proto
  api/notify/v1/types.go
  api/notify/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  pkg/notify/controller/messagerequest/controller.go
  pkg/notify/registry/message/strategy.go
Labels: approved, lgtm, size/S
