Repository tkestack/tke, pull requests merged in 2020-06, with the labels that each got.

#418 fix(cluster): delete addons when delete cluster
  pkg/platform/controller/addon/gpumanager/controller.go
  pkg/platform/controller/addon/ipam/ipam_controller.go
  pkg/platform/controller/addon/tappcontroller/controller.go
  pkg/platform/controller/cluster/deletion/cluster_deleter.go
Labels: lgtm, size/L

#417 fix(cluster): ignore error for cleanup iptables rule, close #398
  pkg/platform/provider/baremetal/cluster/create.go
Labels: lgtm, size/S

#423 fix(cluster): provider-res version
  cmd/tke-installer/app/installer/images/images.go
Labels: approved, lgtm, size/XS

#425 feat(cluster): support customize components args in provider
  go.mod
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/kubeadm.go
  pkg/platform/provider/baremetal/config/config.go
  pkg/platform/provider/baremetal/machine/create.go
  pkg/platform/provider/baremetal/machine/kubeadm.go
  pkg/platform/provider/baremetal/phases/kubelet/kubelet.go
Labels: approved, lgtm, size/L

#428 fix(installer): allow to set version
  cmd/tke-installer/app/installer/installer.go
Labels: approved, lgtm, size/XS

#438 fix: ssh with private key
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/XS

#437 feat(addon): lbcf rest can proxy requests to lbcf driver
  pkg/platform/registry/cluster/storage/lbcf_driver.go
Labels: lgtm, size/M

#440 fix(cluster): get credential not in clusterCredentialRef
  pkg/platform/types/types.go
  pkg/platform/types/v1/types.go
Labels: approved, lgtm, size/S

#441 fix(platform): failed installation of VolumeDecorator
  pkg/platform/controller/addon/storage/volumedecorator/images/images.go
Labels: approved, lgtm, size/XS

#442 fix: can not authn with business ns kubeconfig
  pkg/apiserver/filter/authentication.go
  pkg/auth/authorization/local/authorizer.go
  pkg/business/registry/portal/storage/storage.go
  pkg/business/registry/project/storage/storage.go
  pkg/business/registry/util/auth.go
Labels: approved, lgtm, size/L

#443 feat: change forbidden namespaces
  pkg/business/registry/namespace/validation.go
Labels: approved, lgtm, size/XS

#444 feat(cluster): downgrade coredns to 1.6.7 for keep same with community
  pkg/platform/provider/baremetal/images/images.go
Labels: approved, lgtm, size/XS

#446 fix(installer): add gpu-manager cm
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
  cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
Labels: approved, lgtm, size/S

#447 fix(auth): solve the 1.18 api compatibility problem of policies/users
  pkg/auth/registry/policy/storage/user.go
Labels: approved, lgtm, size/XS

#453 fix(cluster): clean cluster mask when deleting imported cluster
  pkg/platform/provider/imported/cluster/delete.go
  pkg/platform/provider/imported/cluster/provider.go
  pkg/platform/provider/imported/util/mark/mark.go
Labels: approved, lgtm, size/M

#448 fix(notify): allow user-define name for recv and recvgrp
  pkg/notify/registry/receiver/strategy.go
  pkg/notify/registry/receivergroup/strategy.go
Labels: approved, lgtm, size/S

#452 docs: update QRcode
  README.md
  docs/images/wechat.jpeg
Labels: approved, lgtm, size/XS

#454 feat(platform): add tenantID and clusterDisplayName to external
  pkg/platform/controller/addon/prometheus/controller.go
Labels: approved, lgtm, size/XS

#455 hotfix: fix the watch module for chart and apikey
  web/console/Wrapper.tsx
Labels: approved, lgtm, size/S

#456 chore: adjust tke components resources
  cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
  cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
Labels: approved, lgtm, size/XS

#457 fix: Upgrade gpu-manager version to v1.0.4
  pkg/platform/provider/baremetal/images/images.go
  pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml
Labels: approved, lgtm, size/XS

#458 ci: build non-public release everyday
  .github/workflows/release.yml
Labels: approved, lgtm, size/M

#461 ci: optimize release
  .github/workflows/release.yml
Labels: approved, lgtm, size/S

#466 galaxy-ipam support multiarch
  cmd/generate-images/main.go
Labels: approved, lgtm, size/S

#465 fix: docker startup err not detected
  build/docker/tools/tke-installer/install.sh
Labels: approved, lgtm, size/XS

#464 fix: create floatingIP configmap
  pkg/platform/controller/addon/ipam/ipam_controller.go
Labels: approved, lgtm, size/S

#467 fix(cluster): gpu-manager remove read-only on /var/run
  pkg/platform/controller/addon/gpumanager/template/template.go
Labels: approved, lgtm, size/XS

#462 fix: authn returns user info with invalid groups
  pkg/apiserver/filter/authentication.go
  pkg/business/registry/util/auth.go
Labels: approved, lgtm, size/M

#468 fix(cluster): minor version with + for tke cluster
  pkg/util/apiclient/version.go
Labels: approved, lgtm, size/XS

#470 fix(platform): do not sum node filesystem metric
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/XS

#469 fix: rollback unsuitable filter
  pkg/business/registry/portal/storage/storage.go
  pkg/business/registry/project/storage/storage.go
  pkg/business/registry/util/auth.go
Labels: approved, lgtm, size/S

#471 fix(platform): fix syntax error for node filesystem metrics
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/XS

#474 feat: support the fieldRef of env in container
  web/console/lib/ff-component/src/tablepanel/TablePanel.tsx
  web/console/src/modules/cluster/actions/namespaceActions.project.ts
  web/console/src/modules/cluster/actions/namespaceActions.ts
  web/console/src/modules/cluster/actions/resourceActions.ts
  web/console/src/modules/cluster/actions/resourceDetailActions.ts
  web/console/src/modules/cluster/actions/resourceRsActions.ts
  web/console/src/modules/cluster/actions/validateWorkloadActions.ts
  web/console/src/modules/cluster/actions/workflowActions.ts
  web/console/src/modules/cluster/actions/workloadEditActions.ts
  web/console/src/modules/cluster/components/ApplicationApp.project.tsx
  web/console/src/modules/cluster/components/resource/ResourceContainerPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourceDetail.tsx
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourceDetailPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourceModifyHistoryPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNamespaceDetailPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourceNodeDetailPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourceYamlPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerEnvItem.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceTablePanel.tsx
  web/console/src/modules/cluster/constants/Config.ts
  web/console/src/modules/cluster/constants/initState.ts
  web/console/src/modules/cluster/models/ContainerEnv.ts
  web/console/src/modules/cluster/models/ContainerItem.ts
  web/console/src/modules/cluster/models/ResourceDetailState.ts
  web/console/src/modules/cluster/models/index.ts
  web/console/src/modules/cluster/reducers/ResourceDetailReducer.ts
Labels: approved, lgtm, size/XXL

#477 docs: explanation for tokenPrivateKeyFile format
  docs/devel/running-locally.md
Labels: approved, lgtm, size/XS

#472 fix: floatingip config data
  pkg/platform/controller/addon/ipam/ipam_controller.go
Labels: size/XS

#479 feat: change tke resources requirement to 2c4g
  cmd/tke-installer/app/installer/constants/constants.go
  cmd/tke-installer/app/installer/installer.go
  pkg/util/ssh/helpers.go
Labels: approved, lgtm, size/M

#480 feat(installer): add requirement 30GiB available disk space for `/var/lib` in first node
  cmd/tke-installer/app/installer/constants/constants.go
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
  pkg/util/ssh/helpers.go
Labels: approved, lgtm, size/L

#481 feat(policy.json): Support for ProjectAdmin, ProjectMember, and Proje…
  hack/auth/policy.json
Labels: size/S

#483 feat(console): logstash v2
  web/console/Wrapper.tsx
  web/console/config/apiServerVersion.ts
  web/console/config/resource/common/apiVersion.ts
  web/console/config/resource/k8sConfig/otherResource.ts
  web/console/config/resourceConfig.ts
  web/console/config/routerConfig.project.ts
  web/console/helpers/urlUtil.ts
  web/console/package-lock.json
  web/console/src/modules/addon/components/EditAddonPanel.tsx
  web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
  web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
  web/console/src/modules/cluster/actions/clusterActions.ts
  web/console/src/modules/cluster/actions/resourcePodLogActions.ts
  web/console/src/modules/cluster/actions/validateWorkloadActions.ts
  web/console/src/modules/cluster/components/resource/ResourceListPanel.project.tsx
  web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterDetailBasicInfoPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodLogPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerAdvancedPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx
  web/console/src/modules/cluster/constants/ActionType.ts
  web/console/src/modules/cluster/models/ContainerItem.ts
  web/console/src/modules/cluster/models/ResourceDetailState.ts
  web/console/src/modules/cluster/models/index.ts
  web/console/src/modules/cluster/reducers/ResourceDetailReducer.ts
  web/console/src/modules/common/models/CreateResource.ts
  web/console/src/modules/common/models/LogAgent.ts
  web/console/src/modules/common/models/Namespace.ts
  web/console/src/modules/common/models/Resource.ts
  web/console/src/modules/common/models/index.ts
  web/console/src/modules/common/webapi/K8sResourceAPI.ts
  web/console/src/modules/common/webapi/LogAgentAPI.ts
  web/console/src/modules/common/webapi/index.ts
  web/console/src/modules/logStash/WebAPI.ts
  web/console/src/modules/logStash/actions/clusterActions.ts
  web/console/src/modules/logStash/actions/index.ts
  web/console/src/modules/logStash/actions/logActions.ts
  web/console/src/modules/logStash/actions/namespaceActions.ts
  web/console/src/modules/logStash/components/EditLogStashPanel.tsx
  web/console/src/modules/logStash/components/EditOriginContainerItemPanel.tsx
  web/console/src/modules/logStash/components/EditOriginContainerPanel.tsx
  web/console/src/modules/logStash/components/LogSettingTablePanel.tsx
  web/console/src/modules/logStash/components/LogStashActionPanel.tsx
  web/console/src/modules/logStash/components/LogStashApp.tsx
  web/console/src/modules/logStash/components/LogStashHeadPanel.tsx
  web/console/src/modules/logStash/components/LogStashSubHeadPanel.tsx
  web/console/src/modules/logStash/components/LogStashTablePanel.tsx
  web/console/src/modules/logStash/constants/ActionType.ts
  web/console/src/modules/logStash/constants/Config.ts
  web/console/src/modules/logStash/index.tsx
  web/console/src/modules/logStash/models/LogStatsh.ts
  web/console/src/modules/logStash/models/Resource.ts
  web/console/src/modules/logStash/models/RootState.ts
  web/console/src/modules/logStash/reducers/RootReducer.ts
  web/console/src/modules/logStash/router.ts
Labels: approved, lgtm, size/XXL

#485 fix(cluster): kubernetes node versions
  pkg/platform/provider/baremetal/res/res.go
Labels: approved, lgtm, size/XS

#484 fix: remove useless component
  web/installer/public/static/js/installer.js
  web/installer/src/modules/common/components/error/AuthTip.tsx
  web/installer/src/modules/common/components/error/FunctionIsDeveloping.tsx
  web/installer/src/modules/common/components/error/FunctionIsRedirected.tsx
  web/installer/src/modules/common/components/error/index.ts
  web/installer/src/modules/common/components/error/workflowErrorTip.tsx
  web/installer/src/modules/common/components/index.ts
  web/installer/src/modules/common/components/workflowdialog/WorkflowDialog.tsx
  web/installer/src/modules/common/components/workflowdialog/index.tsx
  web/installer/tsconfig.json
Labels: approved, lgtm, size/L

#487 fix(cluster): kubeadm versions
  pkg/platform/provider/baremetal/res/res.go
Labels: approved, lgtm, size/XS

#486 feat(installer): issue etcd client cert for tke components
  cmd/tke-installer/app/installer/installer.go
  pkg/util/pkiutil/pki_helpers.go
  pkg/util/pkiutil/pki_helpers_test.go
Labels: approved, lgtm, size/M

#488 fix(cluster): hash cache in ssh
  pkg/util/hash/hash.go
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/L

#492 feat: extension to business portal
  api/business/types.go
  api/business/v1/generated.pb.go
  api/business/v1/generated.proto
  api/business/v1/types.go
  api/business/v1/types_swagger_doc_generated.go
  api/business/v1/zz_generated.conversion.go
  api/business/v1/zz_generated.deepcopy.go
  api/business/zz_generated.deepcopy.go
  api/openapi/zz_generated.openapi.go
  pkg/business/registry/portal/storage/storage.go
Labels: approved, lgtm, size/M

#491 feat(notify): add clusterDisplayName to alarm variables
  pkg/notify/apiserver/handler.go
Labels: approved, lgtm, size/M

#489 feat(cluster): add kubectl completion bash
  pkg/platform/provider/baremetal/phases/kubelet/kubelet.go
Labels: approved, lgtm, size/XS

#495 fix: fix the reduce method for cpu,mem of node's list
  web/console/src/modules/cluster/components/resource/nodeManage/ComputerTablePanel.tsx
Labels: approved, lgtm, size/M

#498 feat(hack): add actions for ProjectAdmin, ProjectMember and ProjectVi…
  hack/auth/policy.json
Labels: size/S

#503 feat(addon): lbcf rest can proxy requests to lbcf driver
  pkg/platform/registry/cluster/storage/lbcf_driver.go
Labels: approved, lgtm, size/M

#500 feat(console): support path in address
  web/console/src/modules/cluster/actions/validateClusterCreationAction.ts
  web/console/src/modules/cluster/components/clusterManage/CreateClusterPanel.tsx
  web/console/src/modules/cluster/models/ClusterCreationState.ts
Labels: approved, lgtm, size/L

#508 fix: bussiness lbcf can find backgroup
  web/console/src/modules/cluster/actions/resourceActions.project.ts
Labels: lgtm, size/S

#506 fix(cluster): set svc gpu-quota-admission clusterIP
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml
Labels: approved, lgtm, size/XS

#510 fix(cluster): allocate galaxy ipam service ip
  pkg/platform/controller/addon/ipam/ipam_controller.go
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/manifests.go
  pkg/platform/provider/baremetal/constants/constants.go
Labels: approved, lgtm, size/M

#511 fix(cluster): adjust SkipConditions priority
  pkg/platform/provider/baremetal/cluster/provider.go
Labels: approved, lgtm, size/XS

#497 Registry
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/images/images.go
  pkg/platform/provider/baremetal/phases/docker/docker.go
  pkg/platform/provider/baremetal/phases/image/image.go
Labels: approved, lgtm, size/M

#512 fix(platform): update metric k8s_node_status_ready
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, kind/bug, lgtm, size/XS
