Repository tkestack/tke, pull requests merged in 2020-09, with the labels that each got.

#632 feat(prometheus): add more etcd metrics
  pkg/monitor/controller/prometheus/controller.go
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/S

#698 feat: installer fix bug
  web/console/Wrapper.tsx
  web/installer/src/modules/installer/actions/validateActions.ts
  web/installer/src/modules/installer/components/Step3.tsx
  web/installer/src/modules/installer/components/Step6.tsx
  web/installer/src/modules/installer/components/Step9.tsx
Labels: approved, lgtm, size/M

#692 feat(platform): add flag enableMetricsServer for cluster feature
  api/openapi/zz_generated.openapi.go
  api/platform/types.go
  api/platform/v1/generated.pb.go
  api/platform/v1/generated.proto
  api/platform/v1/types.go
  api/platform/v1/zz_generated.conversion.go
  pkg/platform/provider/baremetal/cluster/create.go
Labels: approved, lgtm, size/S

#704 feat(monitor): add cluster display name in overview interface
  api/monitor/types.go
  api/monitor/v1/generated.pb.go
  api/monitor/v1/generated.proto
  api/monitor/v1/types.go
  api/monitor/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  pkg/monitor/registry/overview/cluster/storage/storage.go
  pkg/monitor/util/cache/cache.go
Labels: approved, lgtm, size/L

#702 feat(registry): add registry's domain names to coredns by tenant
  cmd/tke-registry-controller/app/registry.go
  go.mod
  go.sum
  pkg/registry/controller/identityprovider/identityprovider_controller.go
  pkg/registry/util/client.go
  pkg/registry/util/coredns.go
Labels: approved, lgtm, size/L

#699 docs(contributing.md): add contributing document
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/L

#690 fix(console): 修复页面显示中的一些问题
  web/console/Wrapper.tsx
  web/console/src/modules/cluster/actions/validateWorkloadActions.ts
  web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx
  web/console/src/modules/overview/components/OverviewHeadPanel.tsx
  web/console/src/modules/project/components/SelectExistProjectDialog.tsx
Labels: approved, kind/bug, lgtm, size/M

#703 fix(console): 修复创建集群时k8s版本未选择也能创建的bug
  web/console/src/modules/cluster/actions/createICAction.ts
  web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
  web/console/src/modules/cluster/reducers/CreateICReducer.ts
Labels: approved, lgtm, size/S

#708 feat(console): support enable metrics server
  web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
  web/console/src/modules/cluster/actions/createICAction.ts
  web/console/src/modules/cluster/components/clusterManage/CreateICPanel.tsx
  web/console/src/modules/cluster/constants/ActionType.ts
  web/console/src/modules/cluster/models/CreateIC.ts
  web/console/src/modules/cluster/reducers/CreateICReducer.ts
  web/installer/src/modules/installer/WebAPI.ts
Labels: approved, lgtm, size/M

#709 feat(cluster): remove loadbalance because in some case it doesn't wor…
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/provider.go
Labels: approved, kind/feature, lgtm, size/XS

#710 fix(installer): access nodeport cause 63s delay
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/machine/create.go
  pkg/platform/provider/baremetal/machine/provider.go
Labels: approved, size/M

#705 refactor(platform): add more customized hooks
  api/platform/types.go
  api/platform/v1/types.go
  api/platform/validation/cluster.go
  docs/user/cluster/hooks.md
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/cluster/update.go
  pkg/platform/provider/baremetal/machine/create.go
  pkg/platform/provider/baremetal/machine/provider.go
  pkg/platform/provider/baremetal/machine/update.go
  pkg/platform/provider/baremetal/util/util.go
  pkg/util/ssh/ssh.go
Labels: approved, size/L

#691 fix(platform): add nodeAffinity to bind metrics-server to master
  pkg/platform/provider/baremetal/manifests/metrics-server/metrics-server.yaml
Labels: approved, lgtm, size/XS

#715 fix(installer): access nodeport cause 63s delay
  pkg/platform/provider/baremetal/cluster/create.go
Labels: approved, size/XS

#714 docs(installer): update installer guide
  docs/user/tke-installer/normal-installation.md
Labels: approved, size/XS

#713 fix ns
  web/console/src/modules/cluster/actions/namespaceActions.project.ts
  web/console/src/modules/cluster/actions/projectNamespaceActions.project.ts
Labels: approved, size/XS

#717 fix(installer): access nodeport cause 63s delay
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/machine/create.go
Labels: approved, size/XS

#718 fix(install): fix HA config for master host list failed on UI validation
  web/installer/src/modules/installer/WebAPI.ts
Labels: approved, lgtm, size/XS

#720 fix(console): at overview page add cluster display name and fix the use rate bug
  web/console/src/modules/overview/components/ClusterDetailPanel.tsx
  web/console/src/modules/overview/models/RootState.ts
Labels: approved, lgtm, size/S

#723 fix(platform): add master toleration for metrics-server
  pkg/platform/provider/baremetal/manifests/metrics-server/metrics-server.yaml
Labels: approved, lgtm, size/XS

#716 fix(logagent): use get to download log file
  api/logagent/register.go
  api/logagent/types.go
  api/logagent/v1/generated.pb.go
  api/logagent/v1/generated.proto
  api/logagent/v1/register.go
  api/logagent/v1/types.go
  api/logagent/v1/types_swagger_doc_generated.go
  api/logagent/v1/zz_generated.conversion.go
  api/logagent/v1/zz_generated.deepcopy.go
  api/logagent/zz_generated.deepcopy.go
  api/openapi/zz_generated.openapi.go
  pkg/logagent/registry/logagent/storage/filedownload.go
  pkg/logagent/registry/logagent/storage/fileproxy.go
  pkg/logagent/registry/logagent/storage/storage.go
  pkg/logagent/registry/rest/rest.go
Labels: approved, lgtm, size/L

#719 docs(platform): hostname as nodename support
  docs/design-proposals/hostname-as-nodename-support.md
Labels: approved, kind/documentation, lgtm, size/M

#726 feat(install): support enable application
  web/installer/src/modules/installer/WebAPI.ts
  web/installer/src/modules/installer/components/Step5.tsx
  web/installer/src/modules/installer/models/RootState.ts
  web/installer/src/modules/installer/reducers/initState.ts
Labels: approved, lgtm, size/S

#722 fix(platform,monitor): add missing labels for kubelet metrics
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/S

#724 fix(cluster): vip dnat to k8s-svc-ip before kube-proxy running
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/phases/keepalived/keepalived.go
Labels: approved, kind/bug, lgtm, size/M

#729 feat(platform): add machineIP to old nodes
  pkg/platform/controller/cluster/cluster_controller.go
  pkg/platform/controller/machine/machine_controller.go
Labels: approved, kind/feature, lgtm, size/L

#731 fix(console): fix CI can't pick up installer web commit
  web/installer/webpack/webpack.prod.js
Labels: approved, size/XS

#651 build(policy.json): add action of createpodexec to viewer
  hack/auth/policy.json
Labels: do-not-merge/hold, size/XS

#737 fix(notify): make value summary more readable
  pkg/notify/apiserver/handler.go
Labels: approved, lgtm, size/S

#738 fix(installer): miss sysctl.conf
  cmd/tke-installer/app/installer/installer.go
Labels: approved, kind/bug, lgtm, size/XS

#739 fix(platform): update cm from file
  pkg/util/apiclient/idempotency.go
Labels: approved, lgtm, size/S

#740 fix(installer): miss sysctl.conf
  cmd/tke-installer/app/installer/installer.go
  pkg/util/apiclient/idempotency.go
Labels: approved, kind/bug, lgtm, size/S

#743 Feat/skip docker login when no username
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/types/types.go
Labels: approved, kind/feature, lgtm, size/XS

#744 fix(auth): fix invalid number of tokens when empty strings appear
  pkg/auth/util/adapter.go
Labels: approved, lgtm, size/M

#742 fix(installer): skip docker login when no username
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/types/types.go
Labels: approved, lgtm, size/XS

#748 fix(installer): apply configmap ignore resourceVersion
  pkg/util/apiclient/idempotency.go
Labels: approved, kind/bug, lgtm, size/XS

#749 fix(installer): apply configmap ignore resourceVersion
  pkg/util/apiclient/idempotency.go
Labels: approved, lgtm, size/XS

#750 fix(install): fix gputype overwrite enableMetricsServer
  web/installer/src/modules/installer/WebAPI.ts
Labels: approved, lgtm, size/XS

#751 fix(install): allowed es username and passworld empty
  web/installer/src/modules/installer/actions/validateActions.ts
Labels: approved, lgtm, size/XS

#741 fix(monitor): set thanos query timeout to 60s
  pkg/monitor/storage/thanos/metric/metric.go
Labels: approved, lgtm, size/XS

#753 ci(install): highlight build status
  .github/workflows/release.yml
Labels: approved, size/XS

#757 fix(cluster): ingress apigroup replacement problem
  pkg/platform/proxy/extensions/ingress/storage/event.go
Labels: approved, kind/bug, lgtm, size/XS

#755 fix(galaxy): update galaxy version
  pkg/platform/controller/addon/ipam/images/images.go
  pkg/platform/provider/baremetal/phases/galaxy/images/images.go
Labels: approved, kind/feature, lgtm, size/XS

#760 feat(platform): bump up tapp controller version to v1.1.1
  pkg/platform/controller/addon/tappcontroller/images/images.go
Labels: approved, do-not-merge/contains-merge-commits, lgtm, size/XS

#759 feat(console): can enable prometheus in cluster base info page
  web/console/src/modules/addon/actions/addonActions.ts
  web/console/src/modules/addon/components/EditAddonPanel.tsx
  web/console/src/modules/alarmPolicy/components/AlarmPolicyTablePanel.tsx
  web/console/src/modules/cluster/WebAPI/ClusterAPI.ts
  web/console/src/modules/cluster/actions/clusterActions.ts
  web/console/src/modules/cluster/components/clusterManage/ClusterTablePanel.tsx
  web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterDetail.tsx
  web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterDetailBasicInfoPanel.tsx
  web/console/src/modules/cluster/components/resource/clusterInfomation/ClusterPlugInfoPanel.tsx
  web/console/src/modules/common/models/Cluster.ts
  web/console/src/modules/common/webapi/K8sResourceAPI.ts
  web/console/src/modules/common/webapi/PromethusAPI.ts
  web/console/src/modules/common/webapi/index.ts
  web/console/src/modules/uam/actions/userActions.ts
Labels: size/L

#773 ingress apigroup replacement problem
  pkg/platform/proxy/extensions/ingress/storage/event.go
Labels: approved, lgtm, size/XS

#765 feat(registry): enable delete image by digest
  cmd/tke-installer/app/installer/manifests/tke-registry-api/tke-registry-api.yaml
  pkg/registry/apis/config/types.go
  pkg/registry/apis/config/v1/types.go
  pkg/registry/apis/config/v1/zz_generated.conversion.go
  pkg/registry/apis/config/v1/zz_generated.deepcopy.go
  pkg/registry/apis/config/zz_generated.deepcopy.go
  pkg/registry/distribution/distribution.go
Labels: approved, kind/feature, lgtm, size/S

#777 fix(cluster): yaml split error
  pkg/util/apiclient/install.go
Labels: approved, lgtm, size/XS

#776 build(policy.json): add cronhpa related actions to policy.json
  hack/auth/policy.json
Labels: approved, lgtm, size/XS

#756 feat(console): support helm history manifest
  api/application/types.go
  api/application/v1/generated.pb.go
  api/application/v1/generated.proto
  api/application/v1/types.go
  api/application/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  pkg/application/helm/action/history.go
  pkg/application/registry/application/storage/rest_history.go
  web/console/package-lock.json
  web/console/package.json
  web/console/src/modules/application/actions/app/resourceActions.ts
  web/console/src/modules/application/components/app/detail/AppDetail.tsx
  web/console/src/modules/application/components/app/detail/HeaderPanel.tsx
  web/console/src/modules/application/components/app/detail/HistoryTablePanel.tsx
  web/console/src/modules/application/components/app/detail/ResourceTablePanel.tsx
  web/console/src/modules/application/components/app/list/TablePanel.tsx
  web/console/src/modules/application/models/App.ts
  web/console/src/modules/application/router.project.ts
  web/console/src/modules/application/router.ts
Labels: approved, lgtm, size/XL

#747 fix(console): update chart upload guide
  web/console/src/modules/registry/WebAPI.ts
  web/console/src/modules/registry/components/ChartUsageGuideDialog.tsx
  web/console/src/modules/registry/components/chartgroup/list/TablePanel.tsx
Labels: approved, lgtm, size/S

#736 fix(registry): update dependence version of github.com/docker/distribution to fix a crash bug
  go.mod
  go.sum
Labels: approved, kind/bug, lgtm, size/XS

#782 fix(console): hpa.tsx type error
  web/console/src/modules/cluster/components/scale/common/hooks/useNamespaces.ts
  web/console/src/modules/cluster/components/scale/cronhpa/editor/hpa.tsx
  web/console/src/modules/cluster/components/scale/hpa/editor/hpa.tsx
Labels: approved, lgtm, size/M

#783 build(policy.json): change action of listlogcollectors ino listlogcol…
  hack/auth/policy.json
Labels: approved, lgtm, size/XS

#785 Fix/fix corhpa page error
  web/console/src/modules/cluster/components/scale/cronhpa/list/namespaceSelect.tsx
Labels: approved, lgtm, size/XS

#791 docs: release v1.4.0
  CHANGELOG/CHANGELOG-1.4.md
Labels: approved, size/L

#652 feat(platform): support customize flannel backend type
  api/platform/v1/types.go
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/phases/galaxy/galaxy.go
  pkg/platform/provider/baremetal/phases/galaxy/template.go
Labels: approved, lgtm, size/M

#786 fix(cluster): fix hpa and cronhpa problem
  web/console/config/resource/k8sConfig/deployment.ts
  web/console/config/resource/k8sConfig/tapp.ts
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerNumPanel.tsx
  web/console/src/modules/cluster/components/scale/cronhpa/detail/basic.tsx
  web/console/src/modules/cluster/components/scale/cronhpa/editor/hpa.tsx
  web/console/src/modules/cluster/components/scale/cronhpa/list/index.tsx
  web/console/src/modules/cluster/components/scale/cronhpa/list/namespaceSelect.tsx
  web/console/src/modules/cluster/components/scale/hpa/constant.ts
  web/console/src/modules/cluster/components/scale/hpa/detail/basic.tsx
  web/console/src/modules/cluster/components/scale/hpa/editor/hpa.tsx
  web/console/src/modules/cluster/components/scale/hpa/list/index.tsx
  web/console/src/modules/cluster/components/scale/hpa/list/namespaceSelect.tsx
Labels: approved, lgtm, size/L

#778 feat(platform,monitor): add more metrics for k8s node
  pkg/monitor/controller/prometheus/controller.go
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/M
