Repository tkestack/tke, pull requests merged in 2020-02, with the labels that each got.

#124 fix: auth-api and auth-controller json config
  docs/devel/running-locally.md
Labels: size/S

#127 check dst file sha256sum before ssh copy
  pkg/util/ssh/ssh.go
Labels: lgtm, needs-ok-to-test, size/XS

#128 fix: high version of k8s requires configuring cni version
  pkg/platform/provider/baremetal/phases/galaxy/template.go
Labels: needs-ok-to-test, size/XS

#130 Fix: add cluster addons action into category config file
  hack/auth/category.json
Labels: size/XXL

#131 Fix: add nonResourcePath into abac policy config
  cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml
Labels: size/XS

#133 Fix: return empty when get users/groups if not specify tenantID
  pkg/auth/registry/group/storage/storage.go
  pkg/auth/registry/user/storage/storage.go
Labels: size/XS

#135 Fix gateway auth-api proxy config and create admin user conflict
  cmd/tke-auth-api/app/config/config.go
  cmd/tke-auth-api/app/options/auth.go
  cmd/tke-auth-api/app/server.go
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/tke-auth-api/tke-auth-api.yaml
  cmd/tke-installer/app/installer/manifests/tke-gateway/tke-gateway.yaml
  docs/devel/running-locally.md
  pkg/auth/apiserver/apiserver.go
  pkg/auth/authorization/aggregation/aggregation.go
  pkg/auth/authorization/local/authorizer.go
Labels: size/M

#136 feat: change the apiVersion for cluster that version over 1.12
  web/console/config/resource/common/apiVersion.ts
  web/console/config/resourceConfig.ts
  web/console/src/modules/common/components/index.ts
  web/console/src/modules/common/models/index.ts
Labels: size/M

#140 feat: provider-res supports amd64 & arm64 platforms. Update provider-res version.
  build/docker/tools/provider-res/Makefile
  build/docker/tools/provider-res/download.sh
  build/docker/tools/tke-installer/release.sh
Labels: needs-ok-to-test, size/M

#139 Upgrade galaxy/ipam to v1.0.1
  pkg/platform/controller/addon/ipam/images/images.go
  pkg/platform/controller/addon/ipam/ipam_controller.go
  pkg/platform/provider/baremetal/phases/galaxy/images/images.go
  pkg/platform/provider/baremetal/phases/galaxy/template.go
Labels: needs-ok-to-test, size/S

#142 feat: support the cronhpa & tapp
  web/console/Wrapper.tsx
  web/console/config/resource/common/apiVersion.ts
  web/console/config/resource/k8sConfig/otherResource.ts
  web/console/config/resourceConfig.ts
  web/console/helpers/Router.ts
  web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
  web/console/src/modules/cluster/actions/namespaceActions.project.ts
  web/console/src/modules/cluster/actions/projectNamespaceActions.project.ts
  web/console/src/modules/cluster/actions/resourceLogActions.ts
  web/console/src/modules/cluster/actions/subRouterActions.project.ts
  web/console/src/modules/cluster/actions/validateWorkloadActions.ts
  web/console/src/modules/cluster/actions/workloadEditActions.ts
  web/console/src/modules/cluster/actions/workloadSecretActions.ts
  web/console/src/modules/cluster/components/ApplicationApp.project.tsx
  web/console/src/modules/cluster/components/resource/ResourceContainerPanel.tsx
  web/console/src/modules/cluster/components/resource/ResourceListPanel.project.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceAdvancedPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceContainerNumPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceImagePullSecretsPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceEdition/EditResourceVisualizationPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceLogPanel.tsx
  web/console/src/modules/cluster/components/resource/resourceTableOperation/ResourceTablePanel.tsx
  web/console/src/modules/cluster/constants/ActionType.ts
  web/console/src/modules/cluster/constants/Config.ts
  web/console/src/modules/cluster/constants/initState.ts
  web/console/src/modules/cluster/models/WorkloadEdit.ts
  web/console/src/modules/cluster/reducers/RootReducer.project.ts
  web/console/src/modules/cluster/reducers/WorkloadEditReducer.ts
  web/console/src/modules/logStash/constants/Config.ts
  web/console/src/modules/logStash/constants/initState.ts
  web/console/src/modules/logStash/models/ContainerLogs.ts
  web/console/src/modules/persistentEvent/components/ClusterTablePanel.tsx
  web/console/src/modules/project/WebAPI.ts
  web/console/src/modules/uam/WebAPI.ts
  web/console/src/modules/uam/actions/strategyActions.ts
  web/console/src/modules/uam/components/strategy/StrategyDetailsPanel.tsx
  web/console/src/modules/uam/components/strategy/StrategyTablePanel.tsx
Labels: size/XL

#145 Support thanos for tke monitor
  go.mod
  pkg/monitor/apis/config/types.go
  pkg/monitor/apis/config/v1/types.go
  pkg/monitor/apis/config/v1/zz_generated.conversion.go
  pkg/monitor/apis/config/v1/zz_generated.deepcopy.go
  pkg/monitor/apis/config/validation/validation.go
  pkg/monitor/apis/config/zz_generated.deepcopy.go
  pkg/monitor/storage/metric.go
  pkg/monitor/storage/thanos/metric/metric.go
  pkg/monitor/storage/thanos/metric/storage.go
  pkg/platform/controller/addon/prometheus/controller.go
Labels: lgtm, needs-ok-to-test, size/L

#146 Fix construct tkeattr resource for api to list namespaces in the project
  pkg/auth/filter/filter.go
  pkg/auth/filter/filter_test.go
Labels: size/M

#147 Add fieldSelector keyword query for tke-auth resources
  api/auth/v1/conversion.go
  pkg/auth/registry/localgroup/storage/storage.go
  pkg/auth/registry/localidentity/storage/storage.go
  pkg/auth/registry/policy/storage/storage.go
  pkg/auth/registry/role/storage/storage.go
  pkg/auth/util/query.go
Labels: size/L

#148 fix scheduler policy config
  pkg/platform/provider/baremetal/cluster/manifests.go
Labels: needs-ok-to-test, size/XS

#151 feat: build arm64 images via make image PLATFORM=linux_arm64
  Makefile
  build/lib/common.mk
  build/lib/golang.mk
  build/lib/image.mk
  docs/devel/development.md
Labels: lgtm, needs-ok-to-test, size/L

#149 feat: add clusterVersion and clusterDisplayName for business Namespac…
  api/business/types.go
  api/business/v1/generated.pb.go
  api/business/v1/generated.proto
  api/business/v1/types.go
  api/business/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  pkg/business/registry/namespace/storage/storage.go
Labels: lgtm, needs-ok-to-test, size/M

#152 Add headerrequest option for frontproxy gateway
  cmd/tke-gateway/app/config/config.go
  cmd/tke-gateway/app/options/options.go
  cmd/tke-gateway/app/server.go
  pkg/gateway/api/api.go
  pkg/gateway/gateway.go
  pkg/gateway/requestheader/token.go
Labels: size/L

#153 fix
  pkg/platform/provider/baremetal/cluster/manifests.go
Labels: needs-ok-to-test, size/XS

#157 fix: missing network name
  pkg/platform/provider/baremetal/phases/galaxy/template.go
Labels: needs-ok-to-test, size/XS

#154 fix starttime of alarm and add summary variable
  build/docker/tke-notify-api/Dockerfile
  pkg/notify/apiserver/handler.go
Labels: needs-ok-to-test, size/L

#158 Fix: add hints to help users enable docker experimental features
  Makefile
  build/lib/create-manifest.sh
  build/lib/image.mk
  docs/devel/development.md
Labels: needs-ok-to-test, size/L

#160 fix: add node name env for galaxy daemonsets
  pkg/platform/provider/baremetal/phases/galaxy/template.go
Labels: needs-ok-to-test, size/XS
