Repository tkestack/tke, pull requests merged in 2020-07, with the labels that each got.

#513 fix: FromContext panic
  pkg/platform/controller/cluster/cluster_controller.go
  pkg/util/log/context.go
Labels: approved, kind/bug, lgtm, size/S

#514 refactor: cluster and machine deletion log
  pkg/platform/controller/cluster/deletion/cluster_deleter.go
  pkg/platform/controller/machine/deletion/machine_deleter.go
  pkg/platform/controller/machine/machine_controller.go
Labels: approved, lgtm, size/M

#515 fix(installer): set value of new params for tke-monitor-controller
  cmd/tke-installer/app/installer/installer.go
Labels: approved, kind/bug, lgtm, size/M

#516 test: adjust install timeout
  test/e2e_installer/bootstrap_test.go
Labels: approved, lgtm, size/XS

#518 fix(cluster): backport from 1.3 to fix ipam service ip and floating ip cm
  pkg/platform/controller/addon/ipam/ipam_controller.go
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/manifests.go
  pkg/platform/provider/baremetal/constants/constants.go
Labels: kind/bug, size/M

#519 fix(cluster): missing max pods for kubelet
  pkg/platform/provider/baremetal/cluster/kubeadm.go
Labels: approved, lgtm, size/XS

#517 fix(logagent): add logagent in sysinfo
  pkg/gateway/api/sysinfo.go
Labels: approved, lgtm, size/XS

#520 refactor: ssh write file using random tmp dir
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/XS

#522 tkestack 私有化一键部署实践
  docs/guide/zh-CN/best-practices/onestep-tkestack-config-tpl/tke-ha-keepalived.json.j2
  docs/guide/zh-CN/best-practices/onestep-tkestack-config-tpl/tke-ha-lb.json.j2
  docs/guide/zh-CN/best-practices/onestep-tkestack-config-tpl/tke-sigle.json.j2
  docs/guide/zh-CN/best-practices/pic/install-proccess.jpg
  docs/guide/zh-CN/best-practices/pic/onstep-install-process.jpg
  docs/guide/zh-CN/best-practices/pic/proposal.jpg
  docs/guide/zh-CN/best-practices/pic/tkestack-arti.png
  docs/guide/zh-CN/best-practices/tkestack私有化部署最佳实践.md
Labels: size/XL

#525 fix(console): create Import cluster address split error
  web/console/src/modules/cluster/actions/validateClusterCreationAction.ts
  web/console/src/modules/cluster/components/clusterManage/CreateClusterPanel.tsx
Labels: approved, lgtm, size/S

#526 fix(monitor): use prometheus client instead of k8s legacyregistry
  pkg/controller/server.go
  pkg/monitor/storage/project/metrics.go
Labels: approved, kind/bug, lgtm, size/XL

#527 fix(notify): fix wrong notifyAddress stored in tke-notify-api cm
  cmd/tke-notify-api/app/server.go
Labels: approved, kind/bug, lgtm, size/XS

#530 fix(promethues): fix that deploy prometheus on k8s before 1.17 fails
  pkg/monitor/controller/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/controller.go
Labels: approved, kind/bug, lgtm, size/M

#537 feat(platform): bump up tapp controller version to v1.1.0
  pkg/platform/controller/addon/tappcontroller/images/images.go
Labels: approved, kind/feature, lgtm, size/XS

#539 fix(prometheus): add metric prometheus_status_fail to expose status o…
  pkg/monitor/controller/prometheus/controller.go
  pkg/monitor/controller/prometheus/metrics.go
  pkg/platform/controller/addon/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/metrics.go
Labels: approved, lgtm, size/M

#541 feat(prometheus): add metric kube_node_spec_taint
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/XS

#543 fix(prometheus): fix wrong label name of metric prometheus_status_fail
  pkg/platform/controller/addon/prometheus/metrics.go
Labels: approved, lgtm, size/XS

#548 fix(cluster): remove ipam service nodePort
  pkg/platform/controller/addon/ipam/ipam_controller.go
Labels: kind/bug, size/XS

#546 fix(installer): use standard function to parse docker image name
  pkg/util/docker/docker.go
  pkg/util/docker/docker_test.go
Labels: approved, lgtm, size/L

#542 fix(audit): es password decode and es v7 support
  pkg/audit/storage/es/es.go
Labels: approved, kind/bug, lgtm, size/L

#547 Prometheus update
  pkg/monitor/controller/prometheus/controller.go
  pkg/monitor/controller/prometheus/metrics.go
  pkg/platform/controller/addon/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/metrics.go
Labels: approved, lgtm, size/M

#550 fix(cluster): remove CronHPA when deleting cluster
  pkg/platform/controller/addon/cronhpa/controller.go
  pkg/platform/controller/cluster/deletion/cluster_deleter.go
Labels: kind/bug, size/M

#549 build(policy.json): restrict operations on notice by project members …
  hack/auth/policy.json
Labels: approved, lgtm, size/S

#532 feat(monitor): support for querying clusters' overview data
  api/monitor/register.go
  api/monitor/types.go
  api/monitor/v1/generated.pb.go
  api/monitor/v1/generated.proto
  api/monitor/v1/register.go
  api/monitor/v1/types.go
  api/monitor/v1/types_swagger_doc_generated.go
  api/monitor/v1/zz_generated.conversion.go
  api/monitor/v1/zz_generated.deepcopy.go
  api/monitor/zz_generated.deepcopy.go
  api/openapi/zz_generated.openapi.go
  cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
  cmd/tke-monitor-api/app/config/config.go
  cmd/tke-monitor-api/app/options/options.go
  cmd/tke-monitor-api/app/server.go
  pkg/monitor/apiserver/apiserver.go
  pkg/monitor/registry/overview/cluster/storage/storage.go
  pkg/monitor/registry/rest/rest.go
  pkg/monitor/util/cache/cache.go
  pkg/monitor/util/types.go
Labels: approved, good first issue, lgtm, size/XL

#560 refactor: optimize ssh memory
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, platform, size/S

#561 fix(monitor): fix metric conflict in monitor prometheus controller
  pkg/monitor/controller/prometheus/metrics.go
Labels: approved, lgtm, size/XS

#562 feat(prometheus): add node-problem-detector to prometheus addon
  api/monitor/types.go
  api/monitor/v1/generated.pb.go
  api/monitor/v1/generated.proto
  api/monitor/v1/types.go
  api/monitor/v1/types_swagger_doc_generated.go
  api/monitor/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  api/platform/types.go
  api/platform/v1/generated.pb.go
  api/platform/v1/generated.proto
  api/platform/v1/types.go
  api/platform/v1/types_swagger_doc_generated.go
  api/platform/v1/zz_generated.conversion.go
  pkg/monitor/controller/prometheus/controller.go
  pkg/monitor/controller/prometheus/images/images.go
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/images/images.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/XL

#564 fix(cluster): adjust SkipConditions priority
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/machine/provider.go
Labels: kind/bug, size/S

#563 fix(cluster): use advertise address when kubeadm join node
  pkg/platform/provider/baremetal/machine/kubeadm.go
Labels: approved, kind/bug, lgtm, size/XS

#565 fix(go.mod): replace domain-role-manager with a new address
  go.mod
  go.sum
Labels: approved, kind/bug, lgtm, size/XS

#568 fix(installer): modify tke-monitor-api configuration
  cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
Labels: approved, kind/bug, lgtm, size/XS

#571 feat: support overview
  web/console/Wrapper.tsx
  web/console/index.tsx
  web/console/public/static/icon/overviewBlack.svg
  web/console/public/static/icon/overviewCluster.svg
  web/console/public/static/icon/overviewGithub.svg
  web/console/public/static/icon/overviewUser.svg
  web/console/src/modules/overview/WebAPI.ts
  web/console/src/modules/overview/actions/overviewActions.ts
  web/console/src/modules/overview/components/ClusterDetailPanel.tsx
  web/console/src/modules/overview/components/ClusterOverview.tsx
  web/console/src/modules/overview/components/OverviewApp.tsx
  web/console/src/modules/overview/components/OverviewHeadPanel.tsx
  web/console/src/modules/overview/components/QuickHelpPanel.tsx
  web/console/src/modules/overview/components/TipsPanel.tsx
  web/console/src/modules/overview/constants/ActionType.ts
  web/console/src/modules/overview/constants/Config.ts
  web/console/src/modules/overview/index.tsx
  web/console/src/modules/overview/models/RootState.ts
  web/console/src/modules/overview/reducers/RootReducer.ts
  web/console/src/modules/overview/router.ts
  web/console/src/modules/overview/stores/RootStore.ts
Labels: approved, lgtm, size/XL

#572 fix: improve comments
  cmd/tke-installer/app/installer/installer.go
  pkg/gateway/proxy/proxy.go
Labels: size/XS

#580 feat(prometheus): add more metrics scraped by prometheus
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/S

#575 feat(platform): add metrics-server to cluster feature
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/constants/constants.go
  pkg/platform/provider/baremetal/images/images.go
  pkg/platform/provider/baremetal/manifests/metrics-server/metrics-server.yaml
Labels: approved, lgtm, size/L

#570 support wildcard cert
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/installer_test.go
  pkg/util/validation/validation.go
Labels: approved, lgtm, size/M

#587 fix(audit): enable global components audit
  cmd/tke-installer/app/installer/installer.go
Labels: size/S

#581 feat(auth): adapt platform policies and business policies
  go.mod
  pkg/auth/controller/policy/policy_controller.go
  pkg/auth/util/role_manager.go
Labels: size/M

#586 fix(addon): LBCF health check keeps running if fail
  pkg/platform/controller/addon/lbcf/controller.go
Labels: kind/bug, size/S

#590 fix(addon): keep checking health when TAPP addon is in failed state
  pkg/platform/controller/addon/tappcontroller/controller.go
Labels: kind/bug, size/S

#588 fix(addon): keep checking health when TAPP addon is in failed state
  pkg/platform/controller/addon/tappcontroller/controller.go
Labels: kind/bug, size/S

#582 fix typo
  docs/guide/zh-CN/installation/installation-architecture.md
Labels: size/XS

#574 feat(platform): bump up tapp controller version to v1.1.0
  pkg/platform/controller/addon/tappcontroller/images/images.go
Labels: kind/feature, lgtm, size/XS

#589 feat(cluster): auto add authz webhook when open audit
  api/platform/cluster.go
  api/platform/v1/cluster.go
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/cluster/kubeadm.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/config/config.go
  pkg/platform/proxy/client.go
Labels: approved, kind/feature, lgtm, size/S

#592 @yihuachen fix README picture missing issue
  docs/guide/zh-CN/best-practices/offline-pot/docs/offline-pot-pic/one-step-art.png
  docs/guide/zh-CN/best-practices/offline-pot/docs/offline-pot-pic/onestep-design.jpg
Labels: size/XS

#594 fix(platform): support create APIService in apiclient
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/util/apiclient/idempotency.go
  pkg/util/apiclient/install.go
Labels: approved, lgtm, size/M

#595 feat(cluster): add authz webhook if business enabled
  cmd/tke-installer/app/installer/installer.go
  pkg/platform/provider/baremetal/cluster/provider.go
  pkg/platform/provider/baremetal/config/config.go
Labels: kind/feature, size/M

#598 fix(installer): add metrics-server configmap
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
  cmd/tke-installer/app/installer/manifests/tke-platform-controller/tke-platform-controller.yaml
Labels: size/S

#596 build(policy.json): add listuserprojects permission to project roles
  hack/auth/policy.json
Labels: size/XS

#599 feat(gateway): asset routing supports header request
  pkg/gateway/assets/assets.go
  pkg/gateway/gateway.go
Labels: size/XS

#600 fix: dead link
  docs/devel/components.md
  docs/devel/running-locally.md
Labels: size/XS
