Repository tkestack/tke, pull requests merged in 2020-08, with the labels that each got.

#617 fix(cluster): support-authZ-4-global-cluster
  api/platform/v1/cluster.go
  cmd/tke-installer/app/installer/installer.go
  pkg/platform/provider/baremetal/cluster/create.go
  pkg/platform/provider/baremetal/config/config.go
  pkg/platform/provider/baremetal/phases/authzwebhook/authzwebhook.go
  web/console/src/modules/project/components/NamespaceTablePanel.tsx
Labels: size/M

#609 fix(auth): adapt the domain name for platform policies
  pkg/auth/util/group.go
  pkg/auth/util/user.go
Labels: size/S

#616 fix(cluster): query credentials and be compatible with older clusters
  pkg/platform/types/types.go
Labels: size/XS

#614 fix(auth): change users' own password
  pkg/auth/registry/localidentity/validation.go
Labels: approved, lgtm, size/XS

#620 Revert "fix(cluster): query credentials and be compatible with older clusters"
  pkg/platform/types/types.go
Labels: approved, lgtm, size/XS

#622 fix(installer): add retry logic for installer check
  build/docker/tools/tke-installer/install.sh
Labels: approved, size/M

#621 feat: support selector of daemon & tapp when creating service
  web/console/src/modules/cluster/components/resource/resourceEdition/EditServiceWorkloadDialog.tsx
  web/console/src/modules/cluster/constants/Config.ts
Labels: approved, lgtm, size/S

#625 fix(cluster): query credentials and be compatible with older clusters
  pkg/platform/types/types.go
Labels: approved, lgtm, size/XS

#611 feat(prometheus): update prometheus metrics
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: approved, lgtm, size/L

#628 fix(installer): support all in one install
  cmd/tke-installer/app/installer/installer.go
Labels: approved, size/XS

#573 fix(installer): bad field name
  web/installer/src/modules/installer/WebAPI.ts
  web/installer/src/modules/installer/actions/validateActions.ts
  web/installer/src/modules/installer/components/Step4.tsx
  web/installer/src/modules/installer/components/Step9.tsx
  web/installer/src/modules/installer/models/RootState.ts
  web/installer/src/modules/installer/reducers/initState.ts
Labels: approved, lgtm, size/M

#605 feat(monitor): support cluster overview display usage
  api/monitor/types.go
  api/monitor/v1/generated.pb.go
  api/monitor/v1/generated.proto
  api/monitor/v1/types.go
  api/monitor/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  go.mod
  go.sum
  pkg/monitor/registry/overview/cluster/storage/storage.go
  pkg/monitor/util/cache/cache.go
  pkg/monitor/util/types.go
Labels: approved, lgtm, size/L

#633 fix(console): logstash v3 updated
  web/console/Wrapper.tsx
  web/console/helpers/urlUtil.ts
  web/console/src/modules/common/models/Namespace.ts
  web/console/src/modules/logStash/actions/clusterActions.ts
  web/console/src/modules/logStash/actions/editLogStashActions.ts
  web/console/src/modules/logStash/actions/namespaceActions.ts
  web/console/src/modules/logStash/actions/workflowActions.ts
  web/console/src/modules/logStash/components/EditLogStashPanel.tsx
  web/console/src/modules/logStash/components/EditOriginContainerFilePanel.tsx
  web/console/src/modules/logStash/components/EditOriginContainerItemPanel.tsx
  web/console/src/modules/logStash/components/EditOriginContainerPanel.tsx
  web/console/src/modules/logStash/components/ListOriginContainerItemPanel.tsx
  web/console/src/modules/logStash/components/LogDetailPanel.tsx
  web/console/src/modules/logStash/components/LogStashActionPanel.tsx
  web/console/src/modules/logStash/components/LogStashTablePanel.tsx
Labels: approved, lgtm, size/XL

#637 refactor(common): api trunking and combination query support
  docs/design-proposals/api-trunking-combination-query-support.md
  docs/images/api-chunking.png
Labels: approved, size/L

#639 fix(docs): fix dead link
  docs/design-proposals/api-trunking-combination-query-support.md
Labels: approved, size/XS

#640 fix(monitor): solve the problem of checking multiple etcd components
  pkg/monitor/util/cache/cache.go
Labels: approved, lgtm, size/S

#641 fix(console): namespace list for logstash updated
  web/console/src/modules/logStash/WebAPI.ts
Labels: approved, lgtm, size/S

#642 fix(prometheus): fix k8s 1.16 cannot install prometheus
  pkg/monitor/controller/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/controller.go
  pkg/util/apiclient/version.go
Labels: approved, lgtm, size/S

#644 fix(installer): increase-resource
  cmd/tke-installer/app/installer/manifests/tke-platform-api/tke-platform-api.yaml
Labels: approved, size/XS

#647 refactor(common): api trunking and combination query refine
  docs/design-proposals/api-trunking-combination-query-support.md
Labels: approved, size/XS

#649 fix(cluster): update kubelet version compare
  pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
Labels: approved, kind/bug, lgtm, size/M

#656 docs: release v1.3.1
  CHANGELOG/CHANGELOG-1.3.1.md
  docs/guide/zh-CN/installation/installation-procedures.md
  docs/user/tke-installer/installing-offline.md
  docs/user/tke-installer/introduction.md
  docs/user/tke-installer/normal-installation.md
Labels: approved, size/M

#653 fix(cluster): update kubelet version compare
  pkg/platform/provider/baremetal/phases/kubeadm/kubeadm.go
Labels: approved, kind/bug, lgtm, size/M

#661 docs: update to v1.3.1
  README.md
  docs/guide/zh-CN/QuickStart/快速入门.md
  docs/guide/zh-CN/README.md
  docs/guide/zh-CN/installation/installation-procedures.md
  docs/guide/zh-CN/installation/installation-requirement.md
  docs/guide/zh-CN/products/platform/business.md
  docs/guide/zh-CN/products/platform/cluster.md
  docs/guide/zh-CN/products/platform/extender.md
  docs/guide/zh-CN/products/platform/overview.md
  docs/images/overview.png
Labels: approved, kind/documentation, lgtm, size/M

#663 feat(monitor): decouple monitor and business
  api/monitor/types.go
  cmd/tke-installer/app/installer/installer.go
  cmd/tke-installer/app/installer/manifests/tke-monitor-api/tke-monitor-api.yaml
  cmd/tke-monitor-api/app/config/config.go
  cmd/tke-monitor-api/app/options/options.go
  pkg/monitor/registry/overview/cluster/storage/storage.go
  pkg/monitor/util/cache/cache.go
Labels: approved, lgtm, size/M

#654 fix(gateway): webtty add project header
  pkg/gateway/webtty/handler.go
  pkg/gateway/webtty/stream.go
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourcePodRemoteLoginDialog.tsx
Labels: lgtm, size/S

#665 docs: add chinese introduction
  README.md
  docs/guide/zh-CN/README.md
  docs/guide/zh-CN/catalog.md
Labels: approved, kind/documentation, lgtm, size/L

#658 feat(installer): generate image list for specified archs
  cmd/generate-images/main.go
Labels: approved, lgtm, size/XS

#672 docs: update format and fix typo
  docs/guide/zh-CN/QuickStart/examples/创建简单nginx服务.md
  docs/guide/zh-CN/QuickStart/examples/编写Hello-World程序.md
  docs/guide/zh-CN/QuickStart/快速入门.md
  docs/guide/zh-CN/catalog.md
  docs/guide/zh-CN/installation/installation-procedures.md
  docs/guide/zh-CN/installation/installation-requirement.md
  docs/guide/zh-CN/products/business-control-pannel/application/configurations/ConfigMap.md
  docs/guide/zh-CN/products/business-control-pannel/application/configurations/secret.md
  docs/guide/zh-CN/products/business-control-pannel/application/events.md
  docs/guide/zh-CN/products/business-control-pannel/application/log.md
  docs/guide/zh-CN/products/business-control-pannel/application/namespace.md
  docs/guide/zh-CN/products/business-control-pannel/application/services/ingress.md
  docs/guide/zh-CN/products/business-control-pannel/application/services/service.md
  docs/guide/zh-CN/products/business-control-pannel/application/storage/persistent-volume-claim.md
  docs/guide/zh-CN/products/business-control-pannel/application/storage/storave-class.md
  docs/guide/zh-CN/products/business-control-pannel/application/workload/cron-job.md
  docs/guide/zh-CN/products/business-control-pannel/application/workload/daemon-set.md
  docs/guide/zh-CN/products/business-control-pannel/application/workload/deployment.md
  docs/guide/zh-CN/products/business-control-pannel/application/workload/job.md
  docs/guide/zh-CN/products/business-control-pannel/application/workload/resource-limit.md
  docs/guide/zh-CN/products/business-control-pannel/application/workload/stateful-set.md
  docs/guide/zh-CN/products/business-control-pannel/application/workload/tapp.md
  docs/guide/zh-CN/products/business-control-pannel/helm/helm.md
  docs/guide/zh-CN/products/business-control-pannel/monitor-alert/alert.md
  docs/guide/zh-CN/products/business-control-pannel/monitor-alert/notifition.md
  docs/guide/zh-CN/products/business-control-pannel/operation/logcollect.md
  docs/guide/zh-CN/products/business-control-pannel/resource/credentials.md
  docs/guide/zh-CN/products/business-control-pannel/resource/registry.md
  docs/guide/zh-CN/products/controlpannel.md
  docs/guide/zh-CN/products/platform/monitor&alert.md
  docs/guide/zh-CN/products/platform/operation.md
  docs/guide/zh-CN/products/platform/resource.md
  docs/images/audit.png
Labels: approved, kind/documentation, lgtm, size/L

#670 fix(platform): implement deployment rollback for 1.16+ cluster
  go.mod
  go.sum
  pkg/platform/proxy/apps/deployment/storage/rollout.go
  pkg/platform/proxy/apps/deployment/storage/storage.go
  pkg/platform/proxy/apps/rest/rest.go
Labels: approved, kind/bug, lgtm, size/L

#671 fix(console): add sluster version compare in deployment rollback request
  web/console/package-lock.json
  web/console/package.json
  web/console/src/modules/cluster/WebAPI/K8sResourceAPI.ts
  web/console/src/modules/cluster/components/resource/resourceDetail/ResourceRollbackDialog.tsx
  web/console/src/modules/common/models/CreateResource.ts
Labels: approved, kind/bug, lgtm, size/M

#668 fix(cluster): yaml split error
  pkg/util/apiclient/install.go
Labels: approved, lgtm, size/XS

#683 fix(docs): add limitaion to api trunking
  docs/design-proposals/api-trunking-combination-query-support.md
Labels: approved, size/XS

#675 feat(gateway): support component openapi overview
  pkg/gateway/proxy/handler/rewriteproxy/handler.go
  pkg/gateway/proxy/proxy.go
Labels: approved, kind/feature, lgtm, size/L

#667 feat(prometheus): add more info to logs of prometheus install
  pkg/monitor/controller/prometheus/controller.go
  pkg/platform/controller/addon/prometheus/controller.go
Labels: approved, lgtm, size/L

#676 fix(installer): enable-nvidia-device
  pkg/platform/provider/baremetal/manifests/gpu-manager/gpu-manager.yaml
Labels: approved, size/S

#685 fix(lint): make lint error
  pkg/auth/registry/project/storage/group.go
  pkg/auth/registry/project/storage/user.go
  pkg/auth/registry/user/storage/project.go
  pkg/logagent/controller/logagent/logagent_controller.go
  pkg/monitor/controller/prometheus/yamls.go
  pkg/platform/controller/addon/helm/helm_prober.go
  pkg/platform/controller/addon/logcollector/controller.go
  pkg/platform/controller/addon/prometheus/yamls.go
  pkg/platform/provider/baremetal/phases/image/image.go
  pkg/platform/provider/baremetal/phases/kubelet/kubelet.go
Labels: approved, kind/bug, lgtm, size/M
