Repository tkestack/tke, pull requests merged in 2020-03, with the labels that each got.

#161 fix: not update cls quota when update business ns
  pkg/business/controller/namespace/cluster/cluster.go
  pkg/business/controller/namespace/deletion/namespaced_resources_deleter.go
  pkg/business/controller/namespace/namespace_controller.go
  pkg/business/controller/namespace/namespace_health.go
Labels: lgtm, needs-ok-to-test, size/L

#163 Support update auth related resource status with kubectl edit
  pkg/auth/registry/localgroup/strategy.go
  pkg/auth/registry/policy/strategy.go
  pkg/auth/registry/role/strategy.go
  pkg/auth/util/subject.go
Labels: size/M

#164 fix: role policyunbinding empty
  pkg/auth/registry/role/storage/policy.go
  pkg/auth/registry/role/storage/policyunbinding.go
Labels: size/M

#165 fix: Only ask users to enable experimental features when necessary
  Makefile
  build/lib/common.mk
  build/lib/create-manifest.sh
  build/lib/image.mk
Labels: needs-ok-to-test, size/M

#172 feat: add webhook channel type
  api/notify/types.go
  api/notify/v1/generated.pb.go
  api/notify/v1/generated.proto
  api/notify/v1/types.go
  api/notify/v1/types_swagger_doc_generated.go
  api/notify/v1/zz_generated.conversion.go
  api/notify/v1/zz_generated.deepcopy.go
  api/notify/zz_generated.deepcopy.go
  api/openapi/zz_generated.openapi.go
  pkg/notify/controller/messagerequest/controller.go
  pkg/notify/controller/messagerequest/smtp/send.go
  pkg/notify/controller/messagerequest/tencentcloudsms/send.go
  pkg/notify/controller/messagerequest/util/util.go
  pkg/notify/controller/messagerequest/webhook/send.go
  pkg/notify/controller/messagerequest/wechat/send.go
  pkg/notify/registry/channel/validation.go
Labels: lgtm, needs-ok-to-test, size/L

#170 fix: add --iface=$(HOST_IP) arg in flannel
  pkg/platform/provider/baremetal/phases/galaxy/template.go
Labels: lgtm, needs-ok-to-test, size/XS

#167 fix: abnormal status.used data cause panic
  pkg/business/util/resource.go
Labels: lgtm, needs-ok-to-test, size/XS

#174 Fix invalid docker socket path if docker restarts
  pkg/platform/provider/baremetal/phases/galaxy/template.go
Labels: needs-ok-to-test, size/XS

#173 fix: failed to get metrics from cadvisor of k8s v1.12
  pkg/platform/controller/addon/prometheus/yamls.go
Labels: needs-ok-to-test, size/XS

#180 fix: failed to create notify messages sent by webhook channel
  api/notify/types.go
  api/notify/v1/generated.pb.go
  api/notify/v1/generated.proto
  api/notify/v1/types.go
  api/notify/v1/zz_generated.conversion.go
  api/openapi/zz_generated.openapi.go
  pkg/notify/controller/messagerequest/controller.go
  pkg/notify/registry/receiver/validation.go
Labels: needs-ok-to-test, size/S
